import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navigation from "@/components/Navigation";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistMono.className} bg-primary text-foreground antialiased transition-all duration-300`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <header className="mx-auto w-full max-w-3xl space-y-10 p-16 pb-0 max-md:p-8 max-sm:p-4">
            <h1 className="text-center text-4xl font-bold tracking-tighter">
              Youssef Ahrour
            </h1>
            <Navigation />
          </header>
          <main className="mx-auto flex min-h-screen w-full max-w-3xl flex-col items-center gap-16 p-16 max-md:p-8 max-sm:p-4">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
